### ISSUE TITLE
Android X Issue

### ISSUE THREAD

**Issue by Zyzto** [contactlutforrahman/flutter_qr_scanner#3]
Can't run seems it's, maybe due to androidX

C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\FlutterQrScannerPlugin.java:6: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:27: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\FlutterQrScannerPlugin.java:118: error: cannot find symbol
                        ActivityCompat.requestPermissions(context,
                        ^
  symbol:   variable ActivityCompat
  location: class FlutterQrScannerPlugin
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\FlutterQrScannerPlugin.java:151: error: cannot find symbol
                        ActivityCompat.requestPermissions(context,
                        ^
  symbol:   variable ActivityCompat
  location: class FlutterQrScannerPlugin
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:127: error: cannot find symbol
                public void onOpened(@NonNull CameraDevice device) {
                                      ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:133: error: cannot find symbol
                public void onDisconnected(@NonNull CameraDevice device) {
                                            ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:137: error: cannot find symbol
                public void onError(@NonNull CameraDevice device, int error) {
                                     ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:223: error: cannot find symbol
                public void onConfigured(@NonNull CameraCaptureSession session) {
                                          ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:229: error: cannot find symbol
                public void onConfigureFailed(@NonNull CameraCaptureSession session) {
                                               ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                            ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                   ^
  symbol: class NonNull
C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                                                    ^
  symbol: class NonNull
Note: C:\Users\Forev\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_qr_scanner-0.1.5\android\src\main\java\com\github\contactlutforrahman\flutter_qr_scanner\QrCameraC1.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_qr_scanner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by contactlutforrahman** [comment]
Please create your flutter project using Android Studio and select Use AndroidX

**Comment by contactlutforrahman** [comment]
Please use this one : https://pub.dev/packages/flutter_qr_bar_scanner
All the bugs are fixed in this version.
