### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by roelpaulo** [contactlutforrahman/flutter_qr_scanner#4]
`Compiler message:
/ ... /.pub-cache/hosted/pub.dartlang.org/native_device_orientation-0.2.0/lib/native_device_orientation.dart:149:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script ' ... \packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command ' ... \bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Gradle task assembleDebug failed with exit code 1`

**Comment by nandychu** [comment]
Same problem, i forked the project and updated native_device_orientation to 0.3.0

**Comment by contactlutforrahman** [comment]
Please use this one : https://pub.dev/packages/flutter_qr_bar_scanner
All the bugs are fixed in this version.
